Adriftus-Studios/network-script-data

denizen_scripts/global/server/bowtrails.dsc
denizen_scripts/survival/repo-link/spawn_scripts/tutorial.dsc

* Update tutorial.dsc
- Added new locations to the tutorial
- Marketplace, pathing
- Added usage and description for bowtrails
- fixed some capitals and parsing
- Added elevators to tutorial
- minor text fixes
* Update bowtrails.dsc.dsc
- Added usage and description
* Consistency Updates
- Removed raw object comparison
- Fixed fallback definition fallback loop indexing
- Fixed logic check for tutorial runtime

Tutorial Tweaks

---

denizen_scripts/relay/repo-link/Handlers/message_handler.dsc
denizen_scripts/relay/repo-link/Tasks/RFood_DCommand.dsc

Literally just adds a single command to randomly print food to eat. For feature request #39.

Added Food Command

---

denizen_scripts/global/server/commands/discord.dsc
denizen_scripts/survival/repo-link/global_systems/chunk_claim_protection.dsc

Update `Player Exits Area` Event Headers

---

denizen_scripts/global/server/handlers/error_handler.dsc
denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/functions/mod_bans.dsc
denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/functions/mod_commands.dsc
denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/functions/mod_notifier.dsc
denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_actions_inv.dsc
denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_ban_inv.dsc
denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_kick_inv.dsc
denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_send_inv.dsc
denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/tools/mod_report.dsc
denizen_scripts/relay/repo-link/Handlers/message_handler.dsc
denizen_scripts/relay/repo-link/Tasks/Webget_DCommand.dsc
denizen_scripts/survival/repo-link/shops/market_system.dsc

Completes issue: #45 
also some minor cleanups

Feature Request -- Issue 45 - ChrispyMC

---

denizen_scripts/survival/repo-link/items/teleportation_crystals.dsc

* Feature Request -- Issue #46 
Add teleport request messages.
Take items from both players.
Initial teleportation crystal commit.
* Suggested Changes -- Pull Request 62
Squashed commit of the following:
Suggested changes.

Teleportation Crystals: Feature Request -- Issue 46 Part 1

---

denizen_scripts/survival/repo-link/items/teleportation_crystals.dsc
denizen_scripts/survival/repo-link/items/teleportation_shard.dsc
denizen_scripts/survival/repo-link/shops/survivalist_shop.dsc

Squashed commit of the following:
Update item lore.
Replace middle '|' with '+'
Update lore recipe presentation.
Add teleportation shard to the survivalist shop.
Add teleportation shard + recipe.

Teleportation Crystals: Feature Request -- Issue 46 Part 2

---

denizen_scripts/global/server/title_system.dsc
denizen_scripts/survival/repo-link/global_systems/mob_spawn_system.dsc

Fixes for MM Spawning
Remove `stop` on `/title` command.

Mob spawning

---

denizen_scripts/global/server/title_system.dsc
denizen_scripts/survival/repo-link/global_systems/chunk_claim_protection.dsc
denizen_scripts/survival/repo-link/items/system/soul_item_system.dsc
denizen_scripts/survival/repo-link/shops/Cosmetics_Shop.dsc
denizen_scripts/survival/repo-link/shops/claim_upgrades_shop.dsc
denizen_scripts/survival/repo-link/shops/market_system.dsc
denizen_scripts/survival/repo-link/spawn_scripts/tutorial.dsc

- Fix titles being unlocked
- Claim Limit Upgrade is now (Times Bought * 25k)
- Claim group upgrades are now set for beta (most default to off)
- Fix random loss of items in soul forge (?)
- new key for Titles in the Title config: "in_shop: true/false" - defaults to false
- Market system now sells for 30% value, and uses new randomizer method.
- Force newbies into the tutorial

Several updates.

---

denizen_scripts/survival/repo_link/MobScripts/HuskStuff.dsc
denizen_scripts/survival/repo_link/MobScripts/PhantomStuff.dsc
denizen_scripts/survival/repo_link/MobScripts/ShieldBuster.dsc
denizen_scripts/survival/repo_link/MobScripts/SlimeStuff.dsc
denizen_scripts/survival/repo_link/MobScripts/SpiderStuff.dsc

- commentary
- spacing
- logic reversing

Consistency updates

---

denizen_scripts/survival/repo_link/global_systems/economy_test.dsc
denizen_scripts/survival/repo_link/items/system/soul_item_system.dsc

- Balance output is now a rounded currency
- Crafted items now have evident enchantments

Enhancements

---

denizen_scripts/survival/repo_link/systems/scute_dropper.dsc
denizen_scripts/survival/repo_link/systems/vote_handlers.dsc

scutes have a 30% chance per looting level to drop, rounded to 100% at level increments of 3

Created handler for scute dropping from turtles

---

denizen_scripts/survival/repo_link/temporary/world_event.dsc

Updating world event to week two!

---

denizen_scripts/global/server/playerdata.dsc
denizen_scripts/survival/repo_link/items/teleportation_crystals.dsc
denizen_scripts/survival/repo_link/items/teleportation_shard.dsc

Fixing some things in the teleportation shard data.

Teleportation shard name fixes

---

denizen_scripts/global/server/playerdata.dsc
denizen_scripts/survival/repo_link/systems/vote_handlers.dsc

code auditing, better definitions for listed sites, fixed some indentations.

Vote reciever redefinitions

---

denizen_scripts/survival/repo_link/fun/custom_food.dsc

Fixes colorization
Adds:
- berry pie
- apple pie
- honey buns
- carrot cake
- beef stew
- mutton stew

Adding some custom foods

---

denizen_scripts/survival/repo_link/systems/vote_handlers.dsc

added a cancellation at the top, and checks for a full inventory.

Added safeties to vote script

---

denizen_scripts/survival/repo_link/fun/custom_food.dsc

added a flag to check if the player is already opening a food crate.

adding safety to script

---

denizen_scripts/survival/repo_link/systems/vote_handlers.dsc

Replacing old placeholder names, and adding handling to remove keys on use.

switching vote crate injections

---

denizen_scripts/behrcraft/repo_link/Commands/Essentials/Essentials Oxygen.dsc
denizen_scripts/behrcraft/repo_link/Commands/Essentials/Essentials Seen.dsc
denizen_scripts/global/server/dependencies/object_formatting.dsc
denizen_scripts/global/server/handlers/error_handler.dsc
denizen_scripts/relay/repo_link/Handlers/connection.dsc
denizen_scripts/relay/repo_link/Handlers/message.dsc
denizen_scripts/relay/repo_link/commands/haste.dsc
denizen_scripts/relay/repo_link/commands/note.dsc
denizen_scripts/relay/repo_link/commands/rfood.dsc
denizen_scripts/relay/repo_link/commands/tag.dsc
denizen_scripts/relay/repo_link/structure/object_formatting.dsc
denizen_scripts/relay/repo_link/tasks/Error_Response.dsc
denizen_scripts/relay/repo_link/tasks/yayap.dsc
denizen_scripts/survival/repo_link/Commands/token_sender.dsc
denizen_scripts/survival/repo_link/items/system/soul_item_system.dsc
denizen_scripts/survival/repo_link/temporary/world_event.dsc

* hub rename haste command (#275)
* merging hotfixes into stage (#253)
* Update vote_handlers.dsc
* Fixing honey bun recipes
* consistency updates to claims system (#249)
* adding CMD to the items for upcoming textures
* adding chocolate cake.
* Fixing broken event and missing colon
* adjusting stew base items
* correcting mutton stew name
* Create advent_calendar.dsc
* Consistency updates
nothing to see here, surely
Co-authored-by: Bear Riley <46008563+BehrRiley@users.noreply.github.com>
* Legendary item handling creation (#252)
* Update vote_handlers.dsc
* Fixing honey bun recipes
* consistency updates to claims system (#249)
* adding CMD to the items for upcoming textures
* adding chocolate cake.
* Fixing broken event and missing colon
* adjusting stew base items
* correcting mutton …

adding stage in to master

---

denizen_scripts/survival/repo_link/items/system/soul_item_system.dsc

Removed invalid or problematic souls to aid in release
created assignment script, soul command removed.
Turned off debug.

Soul system ready for launch

---

denizen_scripts/hub1/repo_link/Shops/Mystery_Shop.dsc
denizen_scripts/survival/repo_link/shops/Cosmetics_Shop.dsc
denizen_scripts/survival/repo_link/shops/Mystery_Shop.dsc
denizen_scripts/survival/repo_link/shops/claim_upgrades_shop.dsc
denizen_scripts/survival/repo_link/shops/daily_rewards.dsc
denizen_scripts/survival/repo_link/shops/market_system.dsc
denizen_scripts/survival/repo_link/shops/specialty_shop.dsc
denizen_scripts/survival/repo_link/shops/survivalist_shop.dsc
denizen_scripts/survival/repo_link/spawn_scripts/spawn_npc_grim.dsc
denizen_scripts/survival/repo_link/temporary/world_event.dsc

Created or updated assignments for:
mystery shop (hub)
mystery shop (s+)
cosmetic shop
daily rewards
specialty shop
survivalist shop
grim
world event

Modernizing old scripts

---

denizen_scripts/global/server/commands/play.dsc
denizen_scripts/survival/repo_link/MobScripts/mm_gap_filler.dsc
denizen_scripts/survival/repo_link/global_systems/warps.dsc
denizen_scripts/survival/repo_link/shops/market_system.dsc
denizen_scripts/survival/repo_link/spawn_scripts/grim_effects.dsc
denizen_scripts/survival/repo_link/spawn_scripts/spawn_parkour.dsc
denizen_scripts/survival/repo_link/systems/butler.dsc
denizen_scripts/survival/repo_link/systems/vote_handlers.dsc
denizen_scripts/survival/repo_link/temporary/world_event.dsc

Misc fixes 12 14 20

---

denizen_scripts/stage/repo_link/to_update/survival/repo_link/shops/Mystery_Shop.dsc
denizen_scripts/stage/repo_link/to_update/survival/repo_link/shops/market_system.dsc
denizen_scripts/stage/repo_link/updated/hub/repo-link/systems/hub_protection.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/command_scripts/sethome.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/global_systems/bookshelves.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/global_systems/food_gathering_system.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/global_systems/spawner_block_handler.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/global_systems/trash_disposal.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/global_systems/warps.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/spawn_shops/Cosmetics_Shop.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/spawn_shops/claim_upgrades_shop.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/spawn_shops/daily_rewards.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/spawn_shops/spawn_npc_grim.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/spawn_shops/specialty_shop.dsc
denizen_scripts/stage/repo_link/updated/survival/repo-link/spawn_shops/survivalist_shop.dsc

* Update market_system.dsc
updating market to use flags
* Update Mystery_Shop.dsc
changing spacing, changing NBT to flags.

Weekly patches 1 5 21 (#319)
